//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDVBaiKiemTraGiuaKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDVKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDVKhoa()
        {
            this.TDVSinhViens = new HashSet<TDVSinhVien>();
        }
    
        public string TDVMaKH { get; set; }
        public string TDVTenKH { get; set; }
        public Nullable<bool> TDVTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDVSinhVien> TDVSinhViens { get; set; }
    }
}
