//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDVBaiKiemTraGiuaKy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TDVK22CNT3Lesson07DbEntities2 : DbContext
    {
        public TDVK22CNT3Lesson07DbEntities2()
            : base("name=TDVK22CNT3Lesson07DbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TDVKhoa> TDVKhoas { get; set; }
        public virtual DbSet<TDVSinhVien> TDVSinhViens { get; set; }
    }
}
